import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Next13 & Mapbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div
          style={{
            position: "absolute",
            backgroundColor: "pink",
            width: "100%",
            height: "50px",
            zIndex: 10,
            boxShadow: "0 0 15px 15px rgba(0,0,0,0.5)",
          }}
        ></div>
        <div>{children}</div>
      </body>
    </html>
  );
}
